#!/bin/sh
[ "$ACTION" = "ifup" ] || exit 0
[ "$INTERFACE" = "wan_2" ] || exit 0
ATPORT="/dev/ttyUSB2"
send() { printf '%s\r' "$1" >"$ATPORT"; usleep 100000; }
send 'AT+QNWPREFCFG="nr5g_disable_mode",0'
send 'AT+QNWPREFCFG="nsa_nr5g_band",1:3:7:28:38:75:78'
send 'AT+QNWPREFCFG="nr5g_band",1:3:7:28:38:75:78'
EOF